---
- name: install needed packages
  dnf:
    name: redis
    state: latest
    enablerepo: epel

- name: configure redis
  template:
    src: redis.conf.j2
    dest: /etc/redis.conf
    owner: redis
    group: redis
    mode: 0600
    force: true
    backup: true
  notify: restart redis-server

- name: add user nginx to group redis if running togehter with webserver
  user:
   name: nginx
   groups: redis

- name: start and enable redis
  systemd:
    name:    redis
    state:   started
    enabled: true

- name: sysctl vm.overcommit_memory=1
  sysctl: 
    name: vm.overcommit_memory
    value: "1"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.conf
