---
- name: fail early if os is not supported
  assert:
    that: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '8'

- name: set timezone to Europe/Berlin
  timezone:
    name: Europe/Berlin

- name: ensure epel-repository is installed
  package:
    name: epel-release
    state: present
    update_cache: yes

- name: install rpmfusion-free-release
  yum:
    name: https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-8.noarch.rpm
    state: present
    disable_gpg_check: yes

- name: install remi-repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: yes

- name: enable powertools repo
  become: yes
  dnf:
    enablerepo: powertools

- name: install additional packages
  yum:
    name:
      - dnf-plugins-core
      - dnf-automatic
      - policycoreutils-python-utils
      - vim
      - curl
      - gnupg2
      - git
      - ca-certificates
      - tree
      - mlocate
      - dirmngr
      - screen
      - htop
      - net-tools
      - zip
      - unzip
      - bzip2
      - ffmpeg
      - ghostscript
      - python3
      - python3-pip

- name: update and upgrade all packages
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: configure automatic updates
  lineinfile:
    path: /etc/dnf/automatic.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.val }}"
  loop:
    - key: upgrade_type
      val: default
    - key: download_updates
      val: "yes"
    - key: apply_updates
      val: "yes"

- name: enable automatic updates
  service:
    name: dnf-automatic.timer
    state: started
    enabled: yes
