---
- name: add docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: 0644

- name: install docker
  dnf:
    name:
      - docker-ce
    state: latest

- name: install docker lib via pip3
  pip:
    name: docker

- name: enable docker
  systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: yes

- name: add to group docker
  user:
    name: "{{ ansible_env.SUDO_USER }}"
    append: true
    groups: docker
  when: ansible_env.SUDO_USER | default('root') != 'root'
  notify: restart docker

