---
- name: install certbot packages (Let's encrypt ssl certificates)
  dnf:
    name:
      - python3-certbot
      - python3-certbot-nginx
    state: latest
    update_cache: yes
  notify: reload nginx
  when: config_ssl == true

- name: run certbot cert generation and auto nginx config
  become: yes
  shell: "certbot --nginx --non-interactive --agree-tos -m {{ letsencrypt_email }} --domain {{ inventory_hostname }}"
  when: config_ssl == true
  notify: reload nginx

- name: activate http2 protocol in nginx vhost config
  become: yes
  replace:
    path: "/etc/nginx/sites-available/{{ inventory_hostname }}.conf"
    regexp: "^    listen 443 ssl; # managed by Certbot$"
    replace: "    listen 443 ssl http2; # managed by Certbot"
  when: config_ssl == true
  notify: reload nginx

- name: add cron job for certbot renewalbrück
  cron:
    name: Certbot automatic renewal.
    job: "certbot renew --quiet"
    minute: "0"
    hour: "4"
    month: "*"
    user: "root"
  when: config_ssl == true
